# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ClaudeStatusline < Formula
  desc "Fast, minimal statusline generator for Claude Code"
  homepage "https://github.com/jpdarago/claude-statusline"
  version "0.1.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jpdarago/claude-statusline/releases/download/v0.1.2/claude-statusline_0.1.2_darwin_amd64.tar.gz"
      sha256 "ed3f52b4ccf9963643df5517fb5c3a8fded9f701c49d51b47dc915942eb85138"

      define_method(:install) do
        bin.install "claude-statusline"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jpdarago/claude-statusline/releases/download/v0.1.2/claude-statusline_0.1.2_darwin_arm64.tar.gz"
      sha256 "762ebd473a9bb72941d61ae51f9221ff23ba42c0fa8cb1c532156fa7aa9d1def"

      define_method(:install) do
        bin.install "claude-statusline"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jpdarago/claude-statusline/releases/download/v0.1.2/claude-statusline_0.1.2_linux_amd64.tar.gz"
      sha256 "a189e291930e01bf5bca0e5da23267ef973a17d557eb3b1effc50cbca33e9fbe"
      define_method(:install) do
        bin.install "claude-statusline"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jpdarago/claude-statusline/releases/download/v0.1.2/claude-statusline_0.1.2_linux_arm64.tar.gz"
      sha256 "432a1d960d9a6eba16f23acd1c2c11ebc904d9fa275214abcc0f077efdc68e15"
      define_method(:install) do
        bin.install "claude-statusline"
      end
    end
  end

  test do
    assert_match "Opus 4.6",
      pipe_output("#{bin}/claude-statusline", '{"model":{"display_name":"Opus 4.6"}}')
  end
end
