# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Invoice < Formula
  desc "Command line invoice generator"
  homepage "https://github.com/jpdarago/invoice"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jpdarago/invoice/releases/download/v1.0.0/invoice_1.0.0_darwin_amd64.tar.gz"
      sha256 "9ab611fbeb815b39791b3a1645300943e4aa9d015e4b8e296180c9aa67df4d5e"

      define_method(:install) do
        bin.install "invoice"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jpdarago/invoice/releases/download/v1.0.0/invoice_1.0.0_darwin_arm64.tar.gz"
      sha256 "a77956dd75616d8d4749642e0f1a25ff015c6ea4bc38779877eb5f369fb627a9"

      define_method(:install) do
        bin.install "invoice"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jpdarago/invoice/releases/download/v1.0.0/invoice_1.0.0_linux_amd64.tar.gz"
      sha256 "ae498ccf9b6911e401ea635d5020c8e019f804ec171278a1ac8910fe9323d77c"
      define_method(:install) do
        bin.install "invoice"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jpdarago/invoice/releases/download/v1.0.0/invoice_1.0.0_linux_arm64.tar.gz"
      sha256 "88beed871fec710cdae557362f77c7482bc11d37f74378399a81a1ac13971d5d"
      define_method(:install) do
        bin.install "invoice"
      end
    end
  end

  test do
    system "#{bin}/invoice", "--version"
  end
end
