# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Invoice < Formula
  desc "Command line invoice generator"
  homepage "https://github.com/jpdarago/invoice"
  version "1.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jpdarago/invoice/releases/download/v1.0.1/invoice_1.0.1_darwin_amd64.tar.gz"
      sha256 "d81a53da65c68e2a2c4fb7f610ff59f110747e4abbe3c75705ddd1104a9f10f0"

      define_method(:install) do
        bin.install "invoice"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jpdarago/invoice/releases/download/v1.0.1/invoice_1.0.1_darwin_arm64.tar.gz"
      sha256 "ac26c78847582d76008fb82e841dec933d9f26e83bf419e8019fbef00ee92437"

      define_method(:install) do
        bin.install "invoice"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jpdarago/invoice/releases/download/v1.0.1/invoice_1.0.1_linux_amd64.tar.gz"
      sha256 "114d1955324b3cd5a9bea00f3426948b8b0e5aa7ee6ec93fadbcb388a9baee72"
      define_method(:install) do
        bin.install "invoice"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jpdarago/invoice/releases/download/v1.0.1/invoice_1.0.1_linux_arm64.tar.gz"
      sha256 "46b8d8b8b997aaf3fc2d6b782f3c01cadd553d364eb524dc9430e4b167290c04"
      define_method(:install) do
        bin.install "invoice"
      end
    end
  end

  test do
    system "#{bin}/invoice", "--version"
  end
end
