# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lazysnap < Formula
  desc "A TUI for browsing and restoring tarsnap archives"
  homepage "https://github.com/jpdarago/lazysnap"
  version "0.1.0"
  license "MIT"

  depends_on "tarsnap"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jpdarago/lazysnap/releases/download/v0.1.0/lazysnap_0.1.0_darwin_amd64.tar.gz"
      sha256 "1dc3b5b5dd0f1fafe4e193fe199e0991eec57fce64d4e688861652b08bdb15cf"

      define_method(:install) do
        bin.install "lazysnap"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jpdarago/lazysnap/releases/download/v0.1.0/lazysnap_0.1.0_darwin_arm64.tar.gz"
      sha256 "97ad8618d5bda7f9daae442908b8ccba123cbb8457069052b2cc2a918860610e"

      define_method(:install) do
        bin.install "lazysnap"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jpdarago/lazysnap/releases/download/v0.1.0/lazysnap_0.1.0_linux_amd64.tar.gz"
      sha256 "e9a1ef5ad1303375b45a02c71a05b856f506ec232ec7603362f909470eebbe62"
      define_method(:install) do
        bin.install "lazysnap"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jpdarago/lazysnap/releases/download/v0.1.0/lazysnap_0.1.0_linux_arm64.tar.gz"
      sha256 "6c081b59eb0e5517bd4d9f84f99659f187f12d5adff0ccddf3daa47387dbff3b"
      define_method(:install) do
        bin.install "lazysnap"
      end
    end
  end

  test do
    system "#{bin}/lazysnap", "--version"
  end
end
