# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lazysnap < Formula
  desc "A TUI for browsing and restoring tarsnap archives"
  homepage "https://github.com/jpdarago/lazysnap"
  version "0.2.0"
  license "MIT"

  depends_on "tarsnap"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jpdarago/lazysnap/releases/download/v0.2.0/lazysnap_0.2.0_darwin_amd64.tar.gz"
      sha256 "5172ae8af59f4667f030666d8be5314cda8ff20cb652114cbde71d76c9da8090"

      define_method(:install) do
        bin.install "lazysnap"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jpdarago/lazysnap/releases/download/v0.2.0/lazysnap_0.2.0_darwin_arm64.tar.gz"
      sha256 "2a918c419f0ccc99b5f5e71e8e20c8a5d4172379b92ef3f7a44592b366000947"

      define_method(:install) do
        bin.install "lazysnap"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jpdarago/lazysnap/releases/download/v0.2.0/lazysnap_0.2.0_linux_amd64.tar.gz"
      sha256 "0559cb477d266f6b22d8c7c65f985a38d2ff758ddac05ad143ed95f499277956"
      define_method(:install) do
        bin.install "lazysnap"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jpdarago/lazysnap/releases/download/v0.2.0/lazysnap_0.2.0_linux_arm64.tar.gz"
      sha256 "20a2385048820989ad8b2f4cf36dff9551b26da07a52e11d89753861265740e1"
      define_method(:install) do
        bin.install "lazysnap"
      end
    end
  end

  test do
    system "#{bin}/lazysnap", "--version"
  end
end
